services:
  app:
    build: .
    image: bi-sptrans:latest
    ports:
      - "8080:8501"
    environment:
      # Defina aqui ou use um arquivo .env
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT:-5432}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    # Alternativamente, use a URL completa
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
